"""Initial migration

Revision ID: 46718a6e05d4
Revises: 
Create Date: 2025-01-12 18:48:21.660094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46718a6e05d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('person_type', sa.String(length=50), nullable=False),
    sa.Column('registration_date', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('persons')
    # ### end Alembic commands ###
